### ISSUE TITLE
Issue with Windows OS

### ISSUE THREAD

**Issue by ddoz** [receipt-print-hq/chrome-raw-print#15]
i have printer EPSON LQ-310. i can use it in mac but when i use any version of windows os, the printer name didn't show in printer list.  Printer is normal in print test page. i have added vendorId:1208 and productId:71 in manifest file. But nothing happen.

**Comment by mike42** [comment]
I haven't tested on windows, nor with the Epson LQ-310, so I'll assume this is a bug.

It's also possible that the Windows print system has claimed the USB, making it unavailable.

**Comment by ddoz** [comment]
Thank's mike for your respond,
and i say thank you for your repository, i have modified some code for implement in windows OS.
i have solved my problem.
1. convert usbprint(this is usb local printer driver) to winusb with zadig (http://zadig.akeo.ie/)
2. add permission request chrome api (because in chrome windows permission button doesn't exist)
3. add closeDevice after releaseInterface
4. now it's work normally

Thank's 👍

**Comment by t3k0o** [comment]
@ddoz how did you do that? I already added but nothing happens I click on test print

**Comment by ddoz** [comment]
it's too complicated to implement,

**Comment by ddoz** [comment]
It's too complicated to setup this chrome extension on windows, you must turn off Your firewall and antivirus. Did you have followed my step?
