### ISSUE TITLE
How to test without a printer

### ISSUE THREAD

**Issue by vpatidarperficient** [receipt-print-hq/chrome-raw-print#22]
Hi Team,

Could you please help me to how i can test this extension without any printer. Is this support cutepdf or snagit to print.

Thank You

**Comment by mike42** [comment]
This app cannot emulate a printer, and only targets USB devices.

You can use this for raw data transport between a websocket and a USB receipt printer, to make it possible to send the raw, unattended print jobs from client-side javascript running on the same network.
